version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: ""
        LoadBalancerInfo:
          - ContainerName: "dev-yeohaeng-web"
            ContainerPort: 80
          - ContainerName: "nextjs-dev"
            ContainerPort: 3000
        PlatformVersion: "LATEST"